# Generated by Django 4.2.1 on 2023-07-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="email",),
    ]
